# version: 2.1
# orbs:
#   heroku: circleci/heroku@0.0.10
# workflows:
#   heroku_deploy:
#     jobs:
#       - heroku/deploy-via-git
# version: 2.1
# jobs:
#   build:
#     docker:
#       — image: circleci/node:9.11
#     working_directory: ~/repo
#     steps:
#       — checkout
#       - run: npm install
#       — run: npm test
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.11
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
